#!/usr/bin/env bash
#Check to see if curl is installed, 
# if not try to install curl.
#Copyright (c) 2013 Ross Guarino

which curl &> /dev/null

PROGRAM="curl"
SYSTEM=$(uname -s)

success() {
echo "$PROGRAM installed on $SYSTEM" 
}

if [ $? == 0 ]; then
        echo "$PROGRAM already installed"
        exit 0
fi

if [ $SYSTEM = "Linux" ]; then
   OS=$(which yum)
   if [ $OS != 0 ]; then
      sudo apt-get install curl
      res=$?
      success()
      exit res
   fi
   OS=$(which apt-get)
   if [ $? != 0 ]; then
      sudo yum install curl
      res=$?
      success()
      exit res
   fi
fi
if [ $SYSTEM = "FreeBSD" ]; then
   sudo portmaster ftp/curl
   res=$?
   success()
   exit res
fi
