#!/usr/bin/env bash
#Check to see if emacs is installed, 
# if not, try to install emacs.
#Copyright (c) 2013 Ross Guarino

PROGRAM="emacs"
SYSTEM=$(uname -s)

success() {
if [ $res = 0 ]; then
echo "$PROGRAM installed on $SYSTEM"
else
echo "$PROGRAM not installed error [$res]" 
fi
}

#We need emacs 24 so we need to build from source.
install() {
mkdir tmp && cd tmp
wget http://gnu.mirrorcatalogs.com/emacs/emacs-24.3.tar.gz && tar -xf emacs-24.3.tar.gz
cd emacs-24.3
./configure && make && make install
res = $?
cd ../..
}

which $PROGRAM &> /dev/null

if [ $? == 0 ]; then
        echo "$PROGRAM already installed"
        exit 0
fi

if [ $SYSTEM = "Linux" ]; then
   OS=$(which yum)
   if [ $OS != 0 ]; then
      install
      success
      exit $res
   fi
   OS=$(which apt-get)
   if [ $? != 0 ]; then
      install
      success
      exit $res
   fi
fi
if [ $SYSTEM = "FreeBSD" ]; then
   install
   success
   exit $res
fi
