#!/usr/bin/env bash
#Check to see if ssh is installed, 
# if not try to install ssh.
#Copyright (c) 2013 Ross Guarino

PROGRAM="ssh"
SYSTEM=$(uname -s)

success() {
if [ $res = 0 ]; then
echo "$PROGRAM installed on $SYSTEM"
else
echo "$PROGRAM not installed error [$res]" 
fi
}

which $PROGRAM &> /dev/null

if [ $? == 0 ]; then
        echo "$PROGRAM already installed"
        exit 0
fi

if [ $SYSTEM = "Linux" ]; then
   OS=$(which yum)
   if [ $OS != 0 ]; then
      sudo apt-get $PROGRAM
      res=$?
      success
      exit $res
   fi
   OS=$(which apt-get)
   if [ $? != 0 ]; then
      sudo yum install $PROGRAM
      res=$?
      success
      exit $res
   fi
fi
if [ $SYSTEM = "FreeBSD" ]; then
   sudo portmaster security/ssh
   res=$?
   success
   exit $res
fi
