(defun my-go-mode-hook ()
  (add-hook 'before-save-hook 'gofmt-before-save nil t)
  (go-eldoc-setup))

(add-hook 'go-mode-hook 'my-go-mode-hook)
(add-hook 'after-init-hook #'global-flycheck-mode)
(add-hook 'go-mode-hook (lambda ()
			  (set (make-local-variable 'company-backends) '(company-go))
			  (company-mode)))
(add-hook 'go-mode-hook 'go-eldoc-setup)
